name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -e .

    - name: Run tests
      run: |
        pytest tests/ -v

  format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort

    - name: Check code formatting with black
      run: |
        black --check drawn/

    - name: Check import sorting with isort
      run: |
        isort --check-only drawn/
